const reportParams=new URLSearchParams(location.search);
let reportData;
try{reportData=JSON.parse(sessionStorage.getItem(reportParams.get('id')?'aisalyk-saved-report':'aisalyk-draft'));}catch{}
reportData ||= {id:'demo-091',entries:[{name:'Торговая деятельность',index:0,income:1250000},{name:'Общественное питание',index:3,income:350000}],status:'Черновик'};
const fmt=n=>new Intl.NumberFormat('ru-RU',{minimumFractionDigits:2,maximumFractionDigits:2}).format(n);
const safe=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
// Структура и ставки перенесены из предоставленного пользователем бланка.
// Для демонстрационного сценария выручка отнесена к безналичной оплате.
const groups=[
 {name:'Торговая деятельность',index:0,rows:[['До 30 000 000 сомов',50,.5],['В наличной форме',53,4],['В безналичной форме',56,2]],target:2,total:59},
 {name:'Переработка сельскохозяйственной продукции, производство товаров, туроператорская деятельность, разработка программного обеспечения и деятельность в сфере транспорта',index:1,rows:[['В наличной форме',60,4],['В безналичной форме',63,2]],target:1,total:66},
 {name:'Остальные виды деятельности',index:2,rows:[['В наличной форме',67,6],['В безналичной форме',70,4]],target:1,total:73},
 {name:'Общественное питание',index:3,rows:[['В наличной форме',74,6],['В безналичной форме',77,4]],target:1,total:80},
 {name:'Швейное и/или текстильное производство',index:4,rows:[['',81,.25]]},
 {name:'Производство и/или реализация ювелирных изделий',index:5,rows:[['',84,.25]]},
 {name:'Лотерейная деятельность',index:-1,rows:[['',87,4]]},
 {name:'Сауна',index:6,rows:[['До 22.08.2026',90,8],['С 22.08.2026',93,5]],target:0},
 {name:'Бильярд',index:7,rows:[['',96,8]]},
 {name:'Баня',index:8,rows:[['До 22.08.2026',130,8],['С 22.08.2026',133,5]],target:0},
 {name:'Резидент парка креативных индустрий',index:9,rows:[['До 01.08.2026',136,1],['С 01.08.2026',139,0]],target:0},
 {name:'Субъект, применяющий режим, установленный статьёй 324 НК КР',index:10,rows:[['Стоимость товара',142,3]]},
 {name:'Сельскохозяйственные заготовители',index:11,rows:[['',145,.5]]},
 {name:'Сельскохозяйственные заготовители молока',index:12,rows:[['',148,.25]]},
 {name:'Субъект, реализующий товары в адрес обезличенного субъекта (части 1, 2-1, 3, 8 статьи 423 НК КР)',index:13,rows:[['',151,4]]},
 {name:'Субъект СЭЗ, в отношении деятельности, указанной в части 5-1 статьи 430 НК КР, при вывозе товаров',index:14,rows:[['С частичной переработкой',155,1],['В неизменном виде',158,2]],target:0,total:161},
 {name:'Индивидуальный предприниматель, осуществляющий операции и услуги по организации питания учащихся общеобразовательных школ КР',index:15,rows:[['',162,0]]},
 {name:'Обмен и/или передача недвижимого имущества для государственных нужд в соответствии с решением Кабинета Министров',index:16,rows:[['',165,0]]},
 {name:'Деятельность по реализации виртуального актива',index:17,rows:[['',168,8]]},
 {name:'Деятельность вне территории Кыргызской Республики',index:18,rows:[['',171,.1]]}
];
function renderReport(){let total=0,tax=0;const rows=groups.map(g=>{const income=reportData.entries.filter(e=>e.index===g.index).reduce((s,e)=>s+e.income,0);const target=g.target||0;let subtotal=0;const html=g.rows.map(([kind,code,rate],i)=>{const base=i===target?income:0;const due=Math.round(base*rate)/100;total+=base;tax+=due;subtotal+=due;return `<tr class="${base?'filled':''}">${i===0?`<td rowspan="${g.rows.length}" class="name">${g.name}</td>`:''}<td class="kind">${kind}</td><td class="num"><span class="cell-code">${String(code).padStart(3,'0')}</span>${fmt(base)}</td><td class="num"><span class="cell-code">${code+1}</span>${fmt(rate)}</td><td class="num"><span class="cell-code">${code+2}</span>${fmt(due)}</td></tr>`;}).join('');return html+(g.total?`<tr class="subtotal"><td colspan="4" style="text-align:right">ИТОГО сумма налога</td><td class="num"><span class="cell-code">${g.total}</span>${fmt(subtotal)}</td></tr>`:'');}).join('');
document.querySelector('#reportSheet').innerHTML=`<div class="doc-top"><b>FORM STI – 091_10</b><div class="approval">Приложение 3<br>Утвержден приказом ГНС от 24.02.2022 г. № 73<br>(в редакции приказа ГНС от 27.08.2026 г. № П-354)</div></div><h1>ОТЧЁТ ПО ЕДИНОМУ НАЛОГУ</h1><div class="report-types"><span class="code">001</span><span><span class="check">☑</span>ПЕРВОНАЧАЛЬНЫЙ</span><span>☐ УТОЧНЁННЫЙ</span><span>☐ ЛИКВИДАЦИОННЫЙ</span></div><div class="section-title">РАЗДЕЛ I. ИНФОРМАЦИЯ О НАЛОГОПЛАТЕЛЬЩИКЕ</div><table class="identity"><tr><td style="width:38%"><span class="field-title"><b class="code">102</b>ИДЕНТИФИКАЦИОННЫЙ НАЛОГОВЫЙ НОМЕР</span><strong class="digit-boxes">02501201810018</strong></td><td colspan="2"><span class="field-title"><b class="code">103</b>ФИО / НАИМЕНОВАНИЕ НАЛОГОПЛАТЕЛЬЩИКА</span><strong>Общество с ограниченной ответственностью «ТРАНС КАРГО КЕЙ ДЖИ»</strong></td></tr><tr><td colspan="2"><span class="field-title"><b class="code">104</b>КОД И НАИМЕНОВАНИЕ НАЛОГОВОГО ОРГАНА</span><strong>003 — Свердловский р-н</strong></td><td><span class="field-title"><b class="code">115</b>КОНТАКТНЫЙ ТЕЛЕФОН</span><strong>0442162, 0550 320588</strong></td></tr><tr><td><strong>Налоговый период: I квартал 2026</strong></td><td><b class="code">201</b>с <b>01.01.2026</b></td><td><b class="code">202</b>по <b>31.03.2026</b></td></tr></table><div class="section-title">РАЗДЕЛ II. ИНФОРМАЦИЯ О ЕДИНОМ НАЛОГЕ</div><table class="tax-table"><colgroup><col style="width:36%"><col style="width:20%"><col style="width:18%"><col style="width:11%"><col style="width:15%"></colgroup><thead><tr><th colspan="2">ПОКАЗАТЕЛИ</th><th>НАЛОГООБЛАГАЕМАЯ БАЗА<br>(сом)</th><th>СТАВКА НАЛОГА<br>(%)</th><th>СУММА НАЛОГА<br>(сом)</th></tr><tr><th colspan="2">1</th><th>2</th><th>3</th><th>4</th></tr></thead><tbody>${rows}<tr class="total"><td colspan="2">ИТОГО НАЛОГООБЛАГАЕМАЯ БАЗА</td><td class="num"><span class="cell-code">193</span>${fmt(total)}</td><td>ИТОГО НАЛОГ</td><td class="num"><span class="cell-code">194</span>${fmt(tax)}</td></tr></tbody></table><div class="signatures"><div><b>ДЛЯ НАЛОГОПЛАТЕЛЬЩИКА</b>Подпись <span class="signature-line"></span><br>Дата заполнения: 29.09.2026</div><div><b>ДЛЯ НАЛОГОВОГО ОРГАНА</b>Входящий номер __________________<br>Дата принятия ___________________</div></div><div class="doc-footer"><span>ОсОО «ТРАНС КАРГО КЕЙ ДЖИ»</span><span>${safe(reportData.status||'Черновик')} · 29.09.2026</span></div><div class="draft-note">Макет по предоставленному бланку. Для расчёта выручка отнесена к безналичной оплате. Отчёт не отправлен в ГНС.</div>`;
}
document.querySelector('#printReport').onclick=()=>window.print();
if(reportParams.has('id')){const back=document.createElement('a');back.href='journal.html';back.textContent='Вернуться в журнал';back.style.cssText='color:#315b92;text-decoration:none;font-size:13px';document.querySelector('.report-tools').prepend(back);}
if(reportParams.has('edit')){const form=document.createElement('form');form.className='edit-tools';form.innerHTML=reportData.entries.map((e,i)=>`<label>${safe(e.name)} · выручка, сом<input type="number" min="0" max="1000000000000" step="0.01" required name="income-${i}" value="${e.income}"></label>`).join('')+'<button>Применить изменения</button><p class="edit-error" role="alert"></p>';document.querySelector('.report-tools').after(form);form.onsubmit=e=>{e.preventDefault();const values=reportData.entries.map((_,i)=>Number(form.elements[`income-${i}`].value));if(values.some(x=>!Number.isFinite(x)||x<0||x>1e12))return;reportData.entries.forEach((x,i)=>x.income=values[i]);sessionStorage.setItem('aisalyk-draft',JSON.stringify(reportData));renderReport();form.querySelector('.edit-error').textContent='Суммы обновлены. Можно закрыть предпросмотр.';};}
renderReport();
